Repository weble4/linked-house-backend, pull requests merged in 2023-08, with the labels that each got.

#17 customer 관련 클래스 및 profile 클래스 일부 수정
  src/main/java/com/weble/linkedhouse/customer/entity/Customer.java
  src/main/java/com/weble/linkedhouse/customer/entity/CustomerProfile.java
  src/main/java/com/weble/linkedhouse/customer/entity/constant/DeleteRequest.java
  src/main/java/com/weble/linkedhouse/customer/entity/constant/PublicAt.java
  src/main/java/com/weble/linkedhouse/customer/entity/constant/Role.java
  src/main/java/com/weble/linkedhouse/util/AuditingFields.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: enhancement

#18 숙박업소 정보 도메인 구현 완료
  src/main/java/com/weble/linkedhouse/house/entity/House.java
  src/main/java/com/weble/linkedhouse/house/entity/constant/AutoReservation.java
Labels: enhancement

#19 Reservation 첫번째 작업 완료
  settings.gradle
  src/main/java/com/weble/linkedhouse/reservation/entity/Reservation.java
Labels: enhancement

#22 코드 수정 및 호스트 엔티티 작성
  src/main/java/com/weble/linkedhouse/LinkedHouseApplication.java
  src/main/java/com/weble/linkedhouse/customer/entity/Customer.java
  src/main/java/com/weble/linkedhouse/customer/entity/CustomerProfile.java
  src/main/java/com/weble/linkedhouse/host/entity/Host.java
  src/main/java/com/weble/linkedhouse/host/entity/constant/ApproveState.java
  src/main/java/com/weble/linkedhouse/host/entity/constant/LockState.java
  src/main/java/com/weble/linkedhouse/house/entity/House.java
  src/main/java/com/weble/linkedhouse/reservation/entity/Reservation.java
Labels: enhancement

#23 알림 도메인 작성
  src/main/java/com/weble/linkedhouse/notification/entity/Notification.java
  src/main/java/com/weble/linkedhouse/notification/entity/constant/NotificationType.java
Labels: enhancement

#25 예약 취소 엔티티 테이블 작성
  src/main/java/com/weble/linkedhouse/host/entity/Host.java
  src/main/java/com/weble/linkedhouse/house/entity/House.java
  src/main/java/com/weble/linkedhouse/reservation/entity/CancelReservation.java
Labels: enhancement

#32 메시지 도메인 관련 작성
  src/main/java/com/weble/linkedhouse/message/Message.java
  src/main/java/com/weble/linkedhouse/message/constant/ReadCheck.java
Labels: enhancement

#33 게스트 리뷰 도메인 작성 완료
  src/main/java/com/weble/linkedhouse/review/entity/FeedbackCustomer.java
Labels: enhancement

#34 생성자 불필요한 column삭제함
  src/main/java/com/weble/linkedhouse/review/entity/FeedbackCustomer.java
Labels: enhancement

#35 리뷰 호스트 도메인 작성
  src/main/java/com/weble/linkedhouse/message/Message.java
  src/main/java/com/weble/linkedhouse/message/constant/ReadCheck.java
  src/main/java/com/weble/linkedhouse/review/entity/FeedbackHost.java
Labels: enhancement

#36 reviewㅡ호스트/게스트 리뷰
  src/main/java/com/weble/linkedhouse/review/entity/FeedbackCustomer.java
  src/main/java/com/weble/linkedhouse/review/entity/FeedbackHost.java
Labels: enhancement

#38 신고 도메인 작성
  src/main/java/com/weble/linkedhouse/report/entity/Report.java
Labels: enhancement

#40 결제 도메인 작성
  src/main/java/com/weble/linkedhouse/payment/entity/Payment.java
  src/main/java/com/weble/linkedhouse/report/entity/Report.java
Labels: enhancement

#43 Customer API 설계 작성
  build.gradle
  src/main/java/com/weble/linkedhouse/customer/controller/CustomerController.java
  src/main/java/com/weble/linkedhouse/customer/controller/ProfileController.java
  src/main/java/com/weble/linkedhouse/customer/dtos/CustomerDto.java
  src/main/java/com/weble/linkedhouse/customer/dtos/ProfileDtos.java
  src/main/java/com/weble/linkedhouse/customer/dtos/request/SignupRequest.java
  src/main/java/com/weble/linkedhouse/customer/dtos/response/SignupResponse.java
  src/main/java/com/weble/linkedhouse/customer/entity/Customer.java
  src/main/java/com/weble/linkedhouse/customer/entity/CustomerProfile.java
  src/main/java/com/weble/linkedhouse/customer/entity/constant/AuthState.java
  src/main/java/com/weble/linkedhouse/customer/repository/CustomerRepository.java
  src/main/java/com/weble/linkedhouse/customer/repository/ProfileRepository.java
  src/main/java/com/weble/linkedhouse/customer/service/CustomerService.java
  src/main/java/com/weble/linkedhouse/customer/service/ProfileService.java
  src/main/java/com/weble/linkedhouse/message/Message.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: enhancement

#45 validation 추가 수정 및 Custome Exception 클래스 작성
  src/main/java/com/weble/linkedhouse/customer/dtos/request/SignupRequest.java
  src/main/java/com/weble/linkedhouse/customer/service/CustomerService.java
  src/main/java/com/weble/linkedhouse/exception/AlreadyExistEmailException.java
  src/main/java/com/weble/linkedhouse/exception/InvalidSignInInformation.java
  src/main/java/com/weble/linkedhouse/exception/LinkedHouseException.java
  src/main/java/com/weble/linkedhouse/exception/NotExistCustomer.java
  src/main/java/com/weble/linkedhouse/exception/Unauthorized.java
  src/main/java/com/weble/linkedhouse/exception/controller/ExceptionControllerAdvise.java
  src/main/java/com/weble/linkedhouse/exception/response/ErrorResponse.java
Labels: enhancement

#48 Feature/#46 security
  build.gradle
  src/main/java/com/weble/linkedhouse/security/WebSecurityConfig.java
Labels: enhancement

#54 시큐리티 버전 관련 오류 해결 클래스 작성
  src/main/java/com/weble/linkedhouse/customer/service/ProfileService.java
  src/main/java/com/weble/linkedhouse/security/SecurityConfig.java
  src/main/java/com/weble/linkedhouse/security/WebSecurityConfig.java
  src/main/java/com/weble/linkedhouse/util/RequestMatcherBuilder.java
  src/main/resources/application.yml
Labels: enhancement

#56 jwt 관련 라이브러리 및 클래스 추가
  build.gradle
  src/main/java/com/weble/linkedhouse/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/weble/linkedhouse/security/jwt/JwtProperties.java
  src/main/java/com/weble/linkedhouse/security/jwt/JwtTokenProvider.java
  src/main/java/com/weble/linkedhouse/security/jwt/token/RefreshToken.java
  src/main/java/com/weble/linkedhouse/security/jwt/token/TokenDto.java
Labels: enhancement

#57 리뷰 리포지토리 작성 #52
  src/main/java/com/weble/linkedhouse/review/repository/FeedbackCustomerRepository.java
  src/main/java/com/weble/linkedhouse/review/repository/FeedbackHostRepository.java
Labels: enhancement

#63 Security 관련 설정
  .gitignore
  src/main/java/com/weble/linkedhouse/customer/service/CustomerService.java
  src/main/java/com/weble/linkedhouse/exception/JwtNullException.java
  src/main/java/com/weble/linkedhouse/security/SecurityConfig.java
  src/main/java/com/weble/linkedhouse/security/UserDetailsImpl.java
  src/main/java/com/weble/linkedhouse/security/UserDetailsServiceImpl.java
  src/main/java/com/weble/linkedhouse/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/weble/linkedhouse/security/jwt/JwtReturn.java
  src/main/java/com/weble/linkedhouse/security/jwt/JwtTokenProvider.java
  src/main/resources/application.yml
Labels: enhancement

#65 House Repository 구현
  src/main/java/com/weble/linkedhouse/house/dto/HouseDTO.java
  src/main/java/com/weble/linkedhouse/house/entity/constant/AutoReservation.java
  src/main/java/com/weble/linkedhouse/house/repository/HouseRepository.java
Labels: enhancement

#66 Jwt를 이용한 가입 및 로그인 구현
  build.gradle
  src/main/java/com/weble/linkedhouse/customer/controller/CustomerController.java
  src/main/java/com/weble/linkedhouse/customer/dtos/request/LoginRequest.java
  src/main/java/com/weble/linkedhouse/customer/dtos/request/SignupRequest.java
  src/main/java/com/weble/linkedhouse/customer/dtos/response/LoginResponse.java
  src/main/java/com/weble/linkedhouse/customer/dtos/response/SignupResponse.java
  src/main/java/com/weble/linkedhouse/customer/repository/ProfileRepository.java
  src/main/java/com/weble/linkedhouse/customer/service/CustomerService.java
  src/main/java/com/weble/linkedhouse/exception/AlreadyExistEmailException.java
  src/main/java/com/weble/linkedhouse/exception/InvalidSignInInformation.java
  src/main/java/com/weble/linkedhouse/exception/JwtNullException.java
  src/main/java/com/weble/linkedhouse/exception/LinkedHouseException.java
  src/main/java/com/weble/linkedhouse/exception/NotExistCustomer.java
  src/main/java/com/weble/linkedhouse/exception/Unauthorized.java
  src/main/java/com/weble/linkedhouse/exception/response/ErrorMessage.java
  src/main/java/com/weble/linkedhouse/security/SecurityConfig.java
  src/main/java/com/weble/linkedhouse/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/weble/linkedhouse/security/jwt/JwtProperties.java
  src/main/java/com/weble/linkedhouse/security/jwt/JwtTokenProvider.java
  src/main/java/com/weble/linkedhouse/security/jwt/token/RefreshToken.java
  src/main/java/com/weble/linkedhouse/security/jwt/token/RefreshTokenRepository.java
  src/main/java/com/weble/linkedhouse/util/config/RedisConfig.java
  src/main/resources/application.yml
Labels: enhancement

#71 host 관련 삭제
  src/main/java/com/weble/linkedhouse/customer/controller/CustomerController.java
  src/main/java/com/weble/linkedhouse/customer/controller/HostController.java
  src/main/java/com/weble/linkedhouse/customer/controller/ProfileController.java
  src/main/java/com/weble/linkedhouse/host/entity/Host.java
  src/main/java/com/weble/linkedhouse/host/entity/constant/ApproveState.java
  src/main/java/com/weble/linkedhouse/host/entity/constant/LockState.java
  src/main/java/com/weble/linkedhouse/house/entity/House.java
  src/main/java/com/weble/linkedhouse/message/entity/Message.java
  src/main/java/com/weble/linkedhouse/message/entity/constant/ReadCheck.java
  src/main/java/com/weble/linkedhouse/reservation/entity/Reservation.java
  src/main/java/com/weble/linkedhouse/review/entity/FeedbackHost.java
Labels: documentation, enhancement

#73 Feature/#68 review controller 코드 작성
  src/main/java/com/weble/linkedhouse/review/controller/ReviewController.java
  src/main/java/com/weble/linkedhouse/review/dtos/response/CustomerFeedbackResponse.java
  src/main/java/com/weble/linkedhouse/review/dtos/response/CustomerReviewResponse.java
  src/main/java/com/weble/linkedhouse/review/dtos/response/HostFeedbackResponse.java
  src/main/java/com/weble/linkedhouse/review/dtos/response/HostReviewResponse.java
  src/main/java/com/weble/linkedhouse/review/service/FeedbackCustomerService.java
  src/main/java/com/weble/linkedhouse/review/service/FeedbackHostService.java
Labels: enhancement

#83 dto 1개 커밋 + 오타 자 수정
  src/main/java/com/weble/linkedhouse/config/WebSecurityConfig.java
  src/main/java/com/weble/linkedhouse/exception/controller/ExceptionControllerAdvice.java
  src/main/java/com/weble/linkedhouse/review/dtos/response/CustomerFeedbackResponse.java
  src/main/java/com/weble/linkedhouse/review/dtos/response/CustomerReviewResponse.java
  src/main/java/com/weble/linkedhouse/review/dtos/response/HostFeedbackResponse.java
  src/main/java/com/weble/linkedhouse/review/service/FeedbackCustomerService.java
  src/main/java/com/weble/linkedhouse/review/service/FeedbackHostService.java
  src/main/java/com/weble/linkedhouse/review/web/controller/ReviewController.java
  src/main/java/com/weble/linkedhouse/review/web/dtos/request/CustomerReviewRequest.java
  src/main/java/com/weble/linkedhouse/review/web/dtos/request/HostReviewRequest.java
  src/main/java/com/weble/linkedhouse/review/web/dtos/response/CustomerReviewResponse.java
  src/main/java/com/weble/linkedhouse/review/web/dtos/response/HostReviewResponse.java
Labels: enhancement

#77 Customer Info API 작성
  build.gradle
  src/main/java/com/weble/linkedhouse/customer/controller/CustomerController.java
  src/main/java/com/weble/linkedhouse/customer/dtos/CustomerDto.java
  src/main/java/com/weble/linkedhouse/customer/dtos/ProfileDto.java
  src/main/java/com/weble/linkedhouse/customer/dtos/ProfileDtos.java
  src/main/java/com/weble/linkedhouse/customer/dtos/request/PasswordFindRequest.java
  src/main/java/com/weble/linkedhouse/customer/dtos/request/SignupRequest.java
  src/main/java/com/weble/linkedhouse/customer/dtos/request/UpdateRequest.java
  src/main/java/com/weble/linkedhouse/customer/dtos/response/LoginResponse.java
  src/main/java/com/weble/linkedhouse/customer/entity/Customer.java
  src/main/java/com/weble/linkedhouse/customer/entity/CustomerProfile.java
  src/main/java/com/weble/linkedhouse/customer/repository/CustomerRepository.java
  src/main/java/com/weble/linkedhouse/customer/repository/CustomerRepositoryCustom.java
  src/main/java/com/weble/linkedhouse/customer/repository/CustomerRepositoryImpl.java
  src/main/java/com/weble/linkedhouse/customer/service/CustomerService.java
  src/main/java/com/weble/linkedhouse/customer/service/ProfileService.java
  src/main/java/com/weble/linkedhouse/exception/AlreadyAuthentication.java
  src/main/java/com/weble/linkedhouse/exception/AlreadyHasRole.java
  src/main/java/com/weble/linkedhouse/exception/DeleteCustomerException.java
  src/main/java/com/weble/linkedhouse/exception/response/ErrorMessage.java
  src/main/java/com/weble/linkedhouse/house/dto/HouseDTO.java
  src/main/java/com/weble/linkedhouse/security/SecurityConfig.java
  src/main/java/com/weble/linkedhouse/security/UserDetailsImpl.java
  src/main/java/com/weble/linkedhouse/security/UserDetailsServiceImpl.java
  src/main/java/com/weble/linkedhouse/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/weble/linkedhouse/security/jwt/JwtTokenProvider.java
  src/main/java/com/weble/linkedhouse/util/config/QuerydslConfig.java
  src/test/java/com/weble/linkedhouse/customer/service/CustomerServiceTest.java
  src/test/resources/application.yml
Labels: enhancement

#76 Feature/#74 notification api
  src/main/java/com/weble/linkedhouse/notification/controller/NotificationController.java
  src/main/java/com/weble/linkedhouse/notification/dtos/NotificationCreateRequestDto.java
  src/main/java/com/weble/linkedhouse/notification/dtos/NotificationDto.java
  src/main/java/com/weble/linkedhouse/notification/entity/Notification.java
  src/main/java/com/weble/linkedhouse/notification/repository/NotificationRepository.java
  src/main/java/com/weble/linkedhouse/notification/service/NotificationService.java
Labels: enhancement

#85 github action 관련
  .github/workflows/workflow.yml
  src/main/java/com/weble/linkedhouse/customer/dtos/CustomerDto.java
  src/test/java/com/weble/linkedhouse/LinkedHouseApplicationTests.java
  src/test/java/com/weble/linkedhouse/customer/config/TestConfig.java
  src/test/java/com/weble/linkedhouse/customer/service/CustomerServiceTest.java
  src/test/resources/application.yml
Labels: enhancement

#88 유저 관련 작업 마무리 및 Notification 수정
  src/main/java/com/weble/linkedhouse/LinkedHouseApplication.java
  src/main/java/com/weble/linkedhouse/customer/CustomerDeleteScheduled.java
  src/main/java/com/weble/linkedhouse/customer/controller/CustomerController.java
  src/main/java/com/weble/linkedhouse/customer/controller/HostController.java
  src/main/java/com/weble/linkedhouse/customer/dtos/ProfileDto.java
  src/main/java/com/weble/linkedhouse/customer/dtos/request/SignupRequest.java
  src/main/java/com/weble/linkedhouse/customer/dtos/request/UpdateRequest.java
  src/main/java/com/weble/linkedhouse/customer/dtos/response/LoginResponse.java
  src/main/java/com/weble/linkedhouse/customer/entity/Customer.java
  src/main/java/com/weble/linkedhouse/customer/entity/CustomerProfile.java
  src/main/java/com/weble/linkedhouse/customer/repository/DynamicRepoImpl.java
  src/main/java/com/weble/linkedhouse/customer/repository/DynamicRepository.java
  src/main/java/com/weble/linkedhouse/customer/service/CustomerService.java
  src/main/java/com/weble/linkedhouse/exception/NotFoundNotification.java
  src/main/java/com/weble/linkedhouse/exception/response/ErrorMessage.java
  src/main/java/com/weble/linkedhouse/notification/controller/NotificationController.java
  src/main/java/com/weble/linkedhouse/notification/dtos/NotificationCreateRequest.java
  src/main/java/com/weble/linkedhouse/notification/dtos/NotificationCreateRequestDto.java
  src/main/java/com/weble/linkedhouse/notification/dtos/NotificationDto.java
  src/main/java/com/weble/linkedhouse/notification/entity/Notification.java
  src/main/java/com/weble/linkedhouse/notification/repository/NotificationRepository.java
  src/main/java/com/weble/linkedhouse/notification/service/NotificationService.java
  src/main/java/com/weble/linkedhouse/security/UserDetailsImpl.java
  src/main/java/com/weble/linkedhouse/security/jwt/JwtTokenProvider.java
  src/main/java/com/weble/linkedhouse/util/CreateFile.java
  src/main/java/com/weble/linkedhouse/util/config/RedisConfig.java
  src/main/resources/application.yml
  src/test/java/com/weble/linkedhouse/customer/service/CustomerServiceTest.java
  src/test/resources/application.yml
Labels: enhancement

#82 feat : House Controller, Service 구현
  src/main/java/com/weble/linkedhouse/exception/NotExistHouseException.java
  src/main/java/com/weble/linkedhouse/exception/response/ErrorMessage.java
  src/main/java/com/weble/linkedhouse/house/controller/HouseCustomerController.java
  src/main/java/com/weble/linkedhouse/house/controller/HouseHostController.java
  src/main/java/com/weble/linkedhouse/house/dto/HouseDTO.java
  src/main/java/com/weble/linkedhouse/house/dto/request/HostHouseSaveRequest.java
  src/main/java/com/weble/linkedhouse/house/dto/response/HostHouseListResponse.java
  src/main/java/com/weble/linkedhouse/house/dto/response/HostHouseResponse.java
  src/main/java/com/weble/linkedhouse/house/dto/response/HostHouseSaveResponse.java
  src/main/java/com/weble/linkedhouse/house/dto/response/HouseSearchResponseDTO.java
  src/main/java/com/weble/linkedhouse/house/entity/House.java
  src/main/java/com/weble/linkedhouse/house/repository/HouseRepository.java
  src/main/java/com/weble/linkedhouse/house/repository/HouseRepositoryCustom.java
  src/main/java/com/weble/linkedhouse/house/repository/HouseRepositoryCustomImpl.java
  src/main/java/com/weble/linkedhouse/house/service/HouseCustomerService.java
  src/main/java/com/weble/linkedhouse/house/service/HouseHostService.java
  src/main/java/com/weble/linkedhouse/house/service/HouseSpecification.java
  src/main/java/com/weble/linkedhouse/util/config/QueryDslConfig.java
Labels: enhancement

#91 3가지 작업 커밋
  build.gradle
  src/main/java/com/weble/linkedhouse/customer/CustomerDeleteScheduled.java
  src/main/java/com/weble/linkedhouse/customer/controller/CustomerController.java
  src/main/java/com/weble/linkedhouse/customer/dtos/request/UpdateRequest.java
  src/main/java/com/weble/linkedhouse/customer/repository/CustomerRepositoryImpl.java
  src/main/java/com/weble/linkedhouse/customer/service/CustomerService.java
  src/main/java/com/weble/linkedhouse/exception/AboutJwtException.java
  src/main/java/com/weble/linkedhouse/exception/NotFoundChattingRoomException.java
  src/main/java/com/weble/linkedhouse/exception/controller/ExceptionControllerAdvise.java
  src/main/java/com/weble/linkedhouse/exception/response/ErrorMessage.java
  src/main/java/com/weble/linkedhouse/house/controller/HouseCustomerController.java
  src/main/java/com/weble/linkedhouse/house/controller/HouseHostController.java
  src/main/java/com/weble/linkedhouse/house/dto/FilterKeyword.java
  src/main/java/com/weble/linkedhouse/house/dto/HouseDTO.java
  src/main/java/com/weble/linkedhouse/house/dto/SearchKeyword.java
  src/main/java/com/weble/linkedhouse/house/dto/request/HostHouseSaveRequest.java
  src/main/java/com/weble/linkedhouse/house/dto/request/UpdateHouseRequestDto.java
  src/main/java/com/weble/linkedhouse/house/dto/response/HostHouseListResponse.java
  src/main/java/com/weble/linkedhouse/house/dto/response/HostHouseResponse.java
  src/main/java/com/weble/linkedhouse/house/dto/response/HostHouseSaveResponse.java
  src/main/java/com/weble/linkedhouse/house/dto/response/HouseResponseDto.java
  src/main/java/com/weble/linkedhouse/house/dto/response/HouseSearchResponseDTO.java
  src/main/java/com/weble/linkedhouse/house/entity/House.java
  src/main/java/com/weble/linkedhouse/house/entity/HouseImage.java
  src/main/java/com/weble/linkedhouse/house/repository/HouseImageRepository.java
  src/main/java/com/weble/linkedhouse/house/repository/HouseRepository.java
  src/main/java/com/weble/linkedhouse/house/repository/HouseRepositoryCustom.java
  src/main/java/com/weble/linkedhouse/house/repository/HouseRepositoryCustomImpl.java
  src/main/java/com/weble/linkedhouse/house/service/HouseCustomerService.java
  src/main/java/com/weble/linkedhouse/house/service/HouseHostService.java
  src/main/java/com/weble/linkedhouse/house/service/HouseSpecification.java
  src/main/java/com/weble/linkedhouse/message/config/StompHandler.java
  src/main/java/com/weble/linkedhouse/message/config/WebSocketConfig.java
  src/main/java/com/weble/linkedhouse/message/controller/MessageController.java
  src/main/java/com/weble/linkedhouse/message/dto/ChatRoomRequest.java
  src/main/java/com/weble/linkedhouse/message/dto/ChatRoomResponse.java
  src/main/java/com/weble/linkedhouse/message/dto/MessageResponseDto.java
  src/main/java/com/weble/linkedhouse/message/dto/MessageSendDto.java
  src/main/java/com/weble/linkedhouse/message/entity/ChatMessage.java
  src/main/java/com/weble/linkedhouse/message/entity/ChatRoom.java
  src/main/java/com/weble/linkedhouse/message/entity/Message.java
  src/main/java/com/weble/linkedhouse/message/entity/constant/ReadCheck.java
  src/main/java/com/weble/linkedhouse/message/repository/ChatMessageRepository.java
  src/main/java/com/weble/linkedhouse/message/repository/ChatRoomRepository.java
  src/main/java/com/weble/linkedhouse/message/service/ChattingService.java
  src/main/java/com/weble/linkedhouse/notification/entity/constant/NotificationType.java
  src/main/java/com/weble/linkedhouse/security/jwt/token/TokenRequestDto.java
  src/main/java/com/weble/linkedhouse/util/CreateFile.java
  src/main/java/com/weble/linkedhouse/util/UseTimeAop.java
  src/main/java/com/weble/linkedhouse/util/config/QueryDslConfig.java
  src/main/java/com/weble/linkedhouse/util/config/QuerydslConfig.java
  src/main/java/com/weble/linkedhouse/util/config/RedisConfig.java
Labels: enhancement

#97 북마크 기능 작성
  src/main/java/com/weble/linkedhouse/bookmark/controller/BookMarkController.java
  src/main/java/com/weble/linkedhouse/bookmark/dto/BookmarkResponse.java
  src/main/java/com/weble/linkedhouse/bookmark/repository/BookMarkRepository.java
  src/main/java/com/weble/linkedhouse/bookmark/repository/BookMarkRepositoryImpl.java
  src/main/java/com/weble/linkedhouse/bookmark/service/BookMarkService.java
  src/main/java/com/weble/linkedhouse/customer/controller/CustomerController.java
  src/main/java/com/weble/linkedhouse/customer/entity/Customer.java
  src/main/java/com/weble/linkedhouse/customer/entity/CustomerProfile.java
  src/main/java/com/weble/linkedhouse/customer/service/CustomerService.java
  src/main/java/com/weble/linkedhouse/house/entity/House.java
  src/main/java/com/weble/linkedhouse/house/entity/HouseImage.java
  src/main/java/com/weble/linkedhouse/house/service/HouseHostService.java
  src/main/java/com/weble/linkedhouse/message/controller/MessageController.java
  src/main/java/com/weble/linkedhouse/message/service/ChattingService.java
  src/main/java/com/weble/linkedhouse/security/jwt/token/RedisTokenRepository.java
  src/main/java/com/weble/linkedhouse/security/jwt/token/TokenDto.java
  src/main/java/com/weble/linkedhouse/util/config/RedisConfig.java
  src/test/java/com/weble/linkedhouse/customer/service/CustomerServiceTest.java
Labels: enhancement

#102 Reservation Repo, Service, Controller 작성
  .gitignore
  src/main/java/com/weble/linkedhouse/house/entity/HouseImage.java
  src/main/java/com/weble/linkedhouse/reservation/controller/CancelReservationController.java
  src/main/java/com/weble/linkedhouse/reservation/controller/ReservationController.java
  src/main/java/com/weble/linkedhouse/reservation/dto/CancelReservationDTO.java
  src/main/java/com/weble/linkedhouse/reservation/dto/ReservationDTO.java
  src/main/java/com/weble/linkedhouse/reservation/dto/request/CancelReservationRequest.java
  src/main/java/com/weble/linkedhouse/reservation/dto/request/ReservationRequest.java
  src/main/java/com/weble/linkedhouse/reservation/dto/response/ReservationResponse.java
  src/main/java/com/weble/linkedhouse/reservation/entity/CancelReservation.java
  src/main/java/com/weble/linkedhouse/reservation/entity/Reservation.java
  src/main/java/com/weble/linkedhouse/reservation/repository/CancelReservationRepository.java
  src/main/java/com/weble/linkedhouse/reservation/repository/ReservationRepository.java
  src/main/java/com/weble/linkedhouse/reservation/service/CancelReservationService.java
  src/main/java/com/weble/linkedhouse/reservation/service/ReservationService.java
Labels: enhancement

#104 오류 일으키는 부분 fix
  src/main/java/com/weble/linkedhouse/customer/controller/CustomerController.java
  src/main/java/com/weble/linkedhouse/customer/dtos/request/UpdateRequest.java
  src/main/java/com/weble/linkedhouse/house/controller/HouseHostController.java
  src/main/java/com/weble/linkedhouse/house/dto/request/UpdateHouseRequestDto.java
  src/main/java/com/weble/linkedhouse/reservation/controller/ReservationController.java
  src/main/java/com/weble/linkedhouse/util/UseTimeAop.java
Labels: enhancement

#107 revert 후 review단 자료 백업
  src/main/java/com/weble/linkedhouse/review/controller/ReviewController.java
  src/main/java/com/weble/linkedhouse/review/dtos/request/CustomerReviewRequest.java
  src/main/java/com/weble/linkedhouse/review/dtos/request/HostReviewRequest.java
  src/main/java/com/weble/linkedhouse/review/dtos/response/CustomerReviewResponse.java
  src/main/java/com/weble/linkedhouse/review/dtos/response/HostReviewResponse.java
  src/main/java/com/weble/linkedhouse/review/entity/FeedbackCustomer.java
  src/main/java/com/weble/linkedhouse/review/entity/FeedbackHost.java
  src/main/java/com/weble/linkedhouse/review/repository/FeedbackCustomerRepository.java
  src/main/java/com/weble/linkedhouse/review/repository/FeedbackHostRepository.java
  src/main/java/com/weble/linkedhouse/review/service/FeedbackCustomerService.java
  src/main/java/com/weble/linkedhouse/review/service/FeedbackHostService.java
Labels: enhancement

#110 notice 알림 admin단 코드 작성
  src/main/java/com/weble/linkedhouse/admin/controller/AdminController.java
  src/main/java/com/weble/linkedhouse/admin/service/AdminService.java
  src/main/java/com/weble/linkedhouse/notification/dtos/NoticeAll.java
  src/main/java/com/weble/linkedhouse/notification/dtos/NotificationDto.java
  src/main/java/com/weble/linkedhouse/notification/entity/Notification.java
Labels: enhancement

#111 신고 API 작성 , 코드 리펙토링
  src/main/java/com/weble/linkedhouse/bookmark/controller/BookMarkController.java
  src/main/java/com/weble/linkedhouse/bookmark/repository/BookMarkRepository.java
  src/main/java/com/weble/linkedhouse/bookmark/repository/BookMarkRepositoryImpl.java
  src/main/java/com/weble/linkedhouse/bookmark/service/BookMarkService.java
  src/main/java/com/weble/linkedhouse/customer/repository/DynamicRepoImpl.java
  src/main/java/com/weble/linkedhouse/customer/service/CustomerService.java
  src/main/java/com/weble/linkedhouse/exception/NotExistReview.java
  src/main/java/com/weble/linkedhouse/exception/NotReportReview.java
  src/main/java/com/weble/linkedhouse/exception/response/ErrorMessage.java
  src/main/java/com/weble/linkedhouse/notification/entity/Notification.java
  src/main/java/com/weble/linkedhouse/report/controller/ReportController.java
  src/main/java/com/weble/linkedhouse/report/dto/CustomerReviewReportRequest.java
  src/main/java/com/weble/linkedhouse/report/dto/HostReviewReportRequest.java
  src/main/java/com/weble/linkedhouse/report/entity/Report.java
  src/main/java/com/weble/linkedhouse/report/repository/ReportRepository.java
  src/main/java/com/weble/linkedhouse/report/service/ReportService.java
  src/main/java/com/weble/linkedhouse/review/controller/ReviewController.java
  src/main/java/com/weble/linkedhouse/review/dtos/request/CustomerReviewRequest.java
  src/main/java/com/weble/linkedhouse/review/dtos/request/HostReviewRequest.java
  src/main/java/com/weble/linkedhouse/review/entity/FeedbackCustomer.java
  src/main/java/com/weble/linkedhouse/review/entity/FeedbackHost.java
  src/main/java/com/weble/linkedhouse/review/repository/FeedbackCustomerRepository.java
  src/main/java/com/weble/linkedhouse/review/repository/FeedbackHostRepository.java
  src/main/java/com/weble/linkedhouse/review/service/FeedbackCustomerService.java
  src/main/java/com/weble/linkedhouse/review/service/FeedbackHostService.java
  src/main/java/com/weble/linkedhouse/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/weble/linkedhouse/security/jwt/JwtTokenProvider.java
Labels: enhancement

#115 admin의 host review단 작성 완료
  src/main/java/com/weble/linkedhouse/admin/controller/AdminController.java
  src/main/java/com/weble/linkedhouse/admin/service/AdminService.java
  src/main/java/com/weble/linkedhouse/notification/dtos/NoticeAll.java
Labels: enhancement

#122 Test 코드 및 포스트맨을 통한 API 수정
  src/main/java/com/weble/linkedhouse/admin/service/AdminService.java
  src/main/java/com/weble/linkedhouse/bookmark/repository/BookMarkRepositoryImpl.java
  src/main/java/com/weble/linkedhouse/customer/CustomerDeleteScheduled.java
  src/main/java/com/weble/linkedhouse/customer/controller/CustomerController.java
  src/main/java/com/weble/linkedhouse/customer/dtos/request/UpdateRequest.java
  src/main/java/com/weble/linkedhouse/customer/entity/constant/Role.java
  src/main/java/com/weble/linkedhouse/customer/repository/CustomerRepositoryCustom.java
  src/main/java/com/weble/linkedhouse/customer/repository/CustomerRepositoryImpl.java
  src/main/java/com/weble/linkedhouse/customer/service/CustomerService.java
  src/main/java/com/weble/linkedhouse/exception/controller/ExceptionControllerAdvise.java
  src/main/java/com/weble/linkedhouse/house/controller/HouseHostController.java
  src/main/java/com/weble/linkedhouse/house/dto/request/HostHouseSaveRequest.java
  src/main/java/com/weble/linkedhouse/house/dto/request/UpdateHouseRequestDto.java
  src/main/java/com/weble/linkedhouse/house/repository/HouseRepositoryCustom.java
  src/main/java/com/weble/linkedhouse/house/repository/HouseRepositoryCustomImpl.java
  src/main/java/com/weble/linkedhouse/house/service/HouseHostService.java
  src/main/java/com/weble/linkedhouse/notification/controller/NotificationController.java
  src/main/java/com/weble/linkedhouse/notification/dtos/NoticeAll.java
  src/main/java/com/weble/linkedhouse/notification/dtos/NotificationCreateRequest.java
  src/main/java/com/weble/linkedhouse/notification/entity/Notification.java
  src/main/java/com/weble/linkedhouse/notification/repository/NotificationRepository.java
  src/main/java/com/weble/linkedhouse/notification/service/NotificationService.java
  src/main/java/com/weble/linkedhouse/report/controller/ReportController.java
  src/main/java/com/weble/linkedhouse/report/dto/CustomerReviewReportRequest.java
  src/main/java/com/weble/linkedhouse/report/dto/HostReviewReportRequest.java
  src/main/java/com/weble/linkedhouse/report/service/ReportService.java
  src/main/java/com/weble/linkedhouse/reservation/controller/CancelReservationController.java
  src/main/java/com/weble/linkedhouse/reservation/controller/ReservationController.java
  src/main/java/com/weble/linkedhouse/reservation/dto/ReservationDTO.java
  src/main/java/com/weble/linkedhouse/reservation/dto/request/CancelReservationRequest.java
  src/main/java/com/weble/linkedhouse/reservation/dto/request/ReservationRequest.java
  src/main/java/com/weble/linkedhouse/reservation/entity/Reservation.java
  src/main/java/com/weble/linkedhouse/reservation/service/CancelReservationService.java
  src/main/java/com/weble/linkedhouse/reservation/service/ReservationService.java
  src/main/java/com/weble/linkedhouse/review/controller/ReviewController.java
  src/main/java/com/weble/linkedhouse/review/dtos/request/CustomerReviewRequest.java
  src/main/java/com/weble/linkedhouse/review/dtos/response/CustomerReviewResponse.java
  src/main/java/com/weble/linkedhouse/review/dtos/response/HostReviewResponse.java
  src/main/java/com/weble/linkedhouse/review/entity/FeedbackCustomer.java
  src/main/java/com/weble/linkedhouse/review/service/FeedbackCustomerService.java
  src/main/java/com/weble/linkedhouse/review/service/FeedbackHostService.java
  src/main/java/com/weble/linkedhouse/security/UserDetailsServiceImpl.java
  src/main/java/com/weble/linkedhouse/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/weble/linkedhouse/security/jwt/JwtTokenProvider.java
  src/main/java/com/weble/linkedhouse/util/CreateFile.java
  src/main/java/com/weble/linkedhouse/util/UseTimeAop.java
  src/main/java/com/weble/linkedhouse/util/config/BasicConfig.java
  src/main/java/com/weble/linkedhouse/util/logtrace/LogTrace.java
  src/main/java/com/weble/linkedhouse/util/logtrace/ThreadLocalLogTrace.java
  src/main/java/com/weble/linkedhouse/util/logtrace/TraceId.java
  src/main/java/com/weble/linkedhouse/util/logtrace/TraceStatus.java
  src/test/java/com/weble/linkedhouse/bookmark/service/BookMarkServiceTest.java
  src/test/java/com/weble/linkedhouse/customer/service/CustomerServiceTest.java
Labels: bug, enhancement

#124 포스트맨을 이용해 실제 API 수정
  build.gradle
  src/main/java/com/weble/linkedhouse/exception/AlreadyPayReservationException.java
  src/main/java/com/weble/linkedhouse/exception/NotExistReservation.java
  src/main/java/com/weble/linkedhouse/exception/response/ErrorMessage.java
  src/main/java/com/weble/linkedhouse/house/dto/request/HostHouseSaveRequest.java
  src/main/java/com/weble/linkedhouse/house/dto/request/UpdateHouseRequestDto.java
  src/main/java/com/weble/linkedhouse/house/dto/response/HouseResponseDto.java
  src/main/java/com/weble/linkedhouse/house/entity/House.java
  src/main/java/com/weble/linkedhouse/house/service/HouseHostService.java
  src/main/java/com/weble/linkedhouse/payment/controller/PaymentController.java
  src/main/java/com/weble/linkedhouse/payment/dto/request/PaymentRequestDto.java
  src/main/java/com/weble/linkedhouse/payment/dto/response/PaymentResponseDto.java
  src/main/java/com/weble/linkedhouse/payment/entity/Payment.java
  src/main/java/com/weble/linkedhouse/payment/repository/PaymentRepository.java
  src/main/java/com/weble/linkedhouse/payment/service/PaymentService.java
  src/main/java/com/weble/linkedhouse/reservation/controller/CancelReservationController.java
  src/main/java/com/weble/linkedhouse/reservation/controller/ReservationController.java
  src/main/java/com/weble/linkedhouse/reservation/dto/CancelReservationDTO.java
  src/main/java/com/weble/linkedhouse/reservation/dto/request/CancelReservationRequest.java
  src/main/java/com/weble/linkedhouse/reservation/dto/request/ReservationRequest.java
  src/main/java/com/weble/linkedhouse/reservation/dto/response/ReservationResponse.java
  src/main/java/com/weble/linkedhouse/reservation/entity/CancelReservation.java
  src/main/java/com/weble/linkedhouse/reservation/entity/Reservation.java
  src/main/java/com/weble/linkedhouse/reservation/entity/constant/PaymentState.java
  src/main/java/com/weble/linkedhouse/reservation/service/CancelReservationService.java
  src/main/java/com/weble/linkedhouse/reservation/service/ReservationService.java
  src/main/java/com/weble/linkedhouse/review/entity/FeedbackHost.java
  src/main/java/com/weble/linkedhouse/security/jwt/JwtAuthenticationFilter.java
Labels: enhancement

#130 Feature/#128admin
  src/main/java/com/weble/linkedhouse/admin/controller/AdminController.java
  src/main/java/com/weble/linkedhouse/admin/service/AdminFilter.java
  src/main/java/com/weble/linkedhouse/admin/service/AdminService.java
  src/main/java/com/weble/linkedhouse/customer/dtos/ProfileDto.java
  src/main/java/com/weble/linkedhouse/customer/entity/BannedCustomer.java
  src/main/java/com/weble/linkedhouse/customer/entity/Customer.java
  src/main/java/com/weble/linkedhouse/customer/entity/constant/Banneduser.java
  src/main/java/com/weble/linkedhouse/customer/repository/BannedCustomerRepository.java
  src/main/java/com/weble/linkedhouse/customer/repository/CustomerRepository.java
  src/main/java/com/weble/linkedhouse/customer/repository/CustomerRepositoryCustom.java
  src/main/java/com/weble/linkedhouse/customer/repository/CustomerRepositoryImpl.java
Labels: enhancement

#132 feat : House, Reservation 테스트 작성
  src/main/java/com/weble/linkedhouse/house/dto/request/HostHouseSaveRequest.java
  src/test/java/com/weble/linkedhouse/house/service/HouseServiceTest.java
  src/test/java/com/weble/linkedhouse/reservation/service/ReservationServiceTest.java
Labels: enhancement

#134 예약 수락 기능 구현
  README.md
  images/actu.png
  images/customer0.png
  images/customer1.png
  images/erd.png
  images/reser0.png
  images/reser1.png
  images/reser2.png
  images/review.png
  src/main/java/com/weble/linkedhouse/admin/controller/AdminController.java
  src/main/java/com/weble/linkedhouse/customer/controller/CustomerController.java
  src/main/java/com/weble/linkedhouse/customer/service/CustomerService.java
  src/main/java/com/weble/linkedhouse/reservation/controller/ReservationController.java
  src/main/java/com/weble/linkedhouse/reservation/dto/response/ReservationResponse.java
  src/main/java/com/weble/linkedhouse/reservation/entity/Reservation.java
  src/main/java/com/weble/linkedhouse/reservation/entity/constant/ReservationState.java
  src/main/java/com/weble/linkedhouse/reservation/service/ReservationService.java
  src/main/java/com/weble/linkedhouse/security/SecurityConfig.java
  src/main/java/com/weble/linkedhouse/security/jwt/JwtTokenProvider.java
  src/main/java/com/weble/linkedhouse/security/jwt/token/RedisTokenRepository.java
  src/main/java/com/weble/linkedhouse/security/jwt/token/TokenDto.java
  src/test/java/com/weble/linkedhouse/reservation/service/ReservationServiceTest.java
Labels: enhancement

#138 fix : updateHouseTest Error
  src/main/java/com/weble/linkedhouse/house/dto/request/UpdateHouseRequestDto.java
  src/test/java/com/weble/linkedhouse/house/service/HouseServiceTest.java
Labels: bug

#139 #117 테스트 코드 작성 완료
  src/main/java/com/weble/linkedhouse/admin/service/AdminService.java
  src/main/java/com/weble/linkedhouse/review/dtos/response/HostReviewResponse.java
  src/main/java/com/weble/linkedhouse/review/repository/FeedbackHostRepository.java
  src/test/java/com/weble/linkedhouse/admin/service/AdminServiceTest.java
  src/test/java/com/weble/linkedhouse/customer/service/CustomerServiceTest.java
Labels: enhancement

#141 code deploy 작업
  .github/workflows/cd_workflow.yml
  .github/workflows/ci_workflow.yml
  Dockerfile
  README.md
  build.gradle
  images/architecture.png
  src/main/java/com/weble/linkedhouse/admin/controller/AdminController.java
  src/main/java/com/weble/linkedhouse/admin/service/AdminFilter.java
  src/main/java/com/weble/linkedhouse/admin/service/AdminService.java
  src/main/java/com/weble/linkedhouse/customer/controller/CustomerController.java
  src/main/java/com/weble/linkedhouse/customer/dtos/request/UpdateRequest.java
  src/main/java/com/weble/linkedhouse/customer/entity/BannedCustomer.java
  src/main/java/com/weble/linkedhouse/customer/entity/Customer.java
  src/main/java/com/weble/linkedhouse/customer/repository/CustomerRepositoryCustom.java
  src/main/java/com/weble/linkedhouse/customer/repository/CustomerRepositoryImpl.java
  src/main/java/com/weble/linkedhouse/customer/service/CustomerService.java
  src/main/java/com/weble/linkedhouse/house/entity/HouseImage.java
  src/main/java/com/weble/linkedhouse/house/repository/HouseRepositoryCustomImpl.java
  src/main/java/com/weble/linkedhouse/notification/entity/Notification.java
  src/main/java/com/weble/linkedhouse/report/entity/Report.java
  src/main/java/com/weble/linkedhouse/reservation/entity/Reservation.java
  src/main/java/com/weble/linkedhouse/security/SecurityConfig.java
  src/main/resources/application.yml
Labels: enhancement

#144 Admin house조회, 삭제
  src/main/java/com/weble/linkedhouse/admin/controller/AdminController.java
  src/main/java/com/weble/linkedhouse/admin/service/AdminService.java
Labels: enhancement
